deploy:
  runs-on: windows-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-webapp.outputs.webapp-url }}
  permissions:
    id-token: write

  steps:
    - name: Download webapp artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ github.workspace }}/deploy/webapp

    - name: Download api artifact
      uses: actions/download-artifact@v4
      with:
        name: api
        path: ${{ github.workspace }}/deploy/api

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55F5D814DDD143608739A09DB6068299 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03CD6B2F29934EE2BEF1BF18BC04ED5D }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98496DB961F843F09F7C741857ED327C }}

    - name: Check WebApp after download
      run: Get-ChildItem ${{ github.workspace }}/deploy/webapp -Recurse

    - name: Check API after download
      run: Get-ChildItem ${{ github.workspace }}/deploy/api -Recurse

    - name: Deploy Web Application to Azure Web App
      id: deploy-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bordspellenopdracht'
        slot-name: 'Production'
        package: ${{ github.workspace }}/deploy/webapp

    - name: Deploy API to Azure Web App
      id: deploy-api
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bordspellenopdracht'
        slot-name: 'Production'
        package: ${{ github.workspace }}/deploy/api
        virtual-application: '/api'
