name: Build and deploy ASP.Net Core app to Azure Web App - bordspellenopdracht

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  
          
      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build Web Application
        run: dotnet build --configuration Release SpelAvondApp/SpelAvondApp.csproj

      - name: Build API Project
        run: dotnet build --configuration Release SpelAvondApp.API/SpelAvondApp.API.csproj

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal    

      - name: Publish Web Application
        run: dotnet publish -c Release -o ./webapp SpelAvondApp/SpelAvondApp.csproj

      - name: Publish API
        run: dotnet publish -c Release -o ./api SpelAvondApp.API/SpelAvondApp.API.csproj

      - name: Upload webapp artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./webapp

      - name: Upload api artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ./api

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download webapp artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Download api artifact
        uses: actions/download-artifact@v4
        with:
          name: api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55F5D814DDD143608739A09DB6068299 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03CD6B2F29934EE2BEF1BF18BC04ED5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98496DB961F843F09F7C741857ED327C }}

      - name: Deploy Web Application to Azure Web App
        id: deploy-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bordspellenopdracht'
          slot-name: 'Production'
          package: .

      - name: Deploy API to Azure Web App
        id: deploy-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bordspellenopdracht'
          slot-name: 'Production'
          package: ./api
          virtual-application: '/api'
